[project]
name = "codeinspector"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "gitpython>=3.1.44",
    "jupyter-repo2docker>=2024.7.0",
    "osfclient>=0.0.5",
]
